In [2]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('CNN_Articels_clean.csv')

In [6]:
df.head()

,Index,Author,Date published,Category,Section,Url,Headline,Description,Keywords,Second headline,Article text
0,0,"Jacopo Prisco, CNN",2021-07-15 02:46:59,news,world,https://www.cnn.com/2021/07/14/world/tusimple-...,"There's a shortage of truckers, but TuSimple t...",The e-commerce boom has exacerbated a global t...,"world, There's a shortage of truckers, but TuS...","There's a shortage of truckers, but TuSimple t...","(CNN)Right now, there's a shortage of truck d..."
1,1,"Stephanie Bailey, CNN",2021-05-12 07:52:09,news,world,https://www.cnn.com/2021/05/12/world/ironhand-...,Bioservo's robotic 'Ironhand' could protect fa...,Working in a factory can mean doing the same t...,"world, Bioservo's robotic 'Ironhand' could pro...",A robotic 'Ironhand' could protect factory wor...,(CNN)Working in a factory or warehouse can me...
2,2,"Words by Stephanie Bailey, video by Zahra Jamshed",2021-06-16 02:51:30,news,asia,https://www.cnn.com/2021/06/15/asia/swarm-robo...,This swarm of robots gets smarter the more it ...,"In a Hong Kong warehouse, a swarm of autonomou...","asia, This swarm of robots gets smarter the mo...",This swarm of robots gets smarter the more it ...,"(CNN)In a Hong Kong warehouse, a swarm of aut..."
3,3,Kathryn Vasel,2022-03-18 14:37:21,business,success,https://www.cnn.com/2022/03/18/success/pandemi...,"Two years later, remote work has changed milli...",Here's a look at how the pandemic reshaped peo...,"success, Two years later, remote work has chan...","Two years later, remote work has changed milli...",The pandemic thrust the working world into a n...
4,4,"Paul R. La Monica, CNN Business",2022-03-19 11:41:08,business,investing,https://www.cnn.com/2022/03/19/investing/march...,Why March is so volatile for stocks - CNN,March Madness isn't just for college basketbal...,"investing, Why March is so volatile for stocks...",Why March is so volatile for stocks,New York (CNN Business)March Madness isn't jus...

In [12]:
df.drop(columns= ['Index', 'Author', 'Date published',	'Category', 'Section', 'Url', 'Description', 'Headline', 'Second headline'], inplace=True, axis=1)

In [24]:
df['Article text'] = df['Article text'].str.replace('(CNN)', '')
df['Keywords'] = df['Keywords'].str.replace('- CNN', '')
df['Article text'] = df['Article text'].str.strip()
df['Keywords'] = df['Keywords'].str.strip()

In [25]:
df.head()

,Keywords,Article text
0,"world, There's a shortage of truckers, but TuS...","Right now, there's a shortage of truck drivers..."
1,"world, Bioservo's robotic 'Ironhand' could pro...",Working in a factory or warehouse can mean doi...
2,"asia, This swarm of robots gets smarter the mo...","In a Hong Kong warehouse, a swarm of autonomou..."
3,"success, Two years later, remote work has chan...",The pandemic thrust the working world into a n...
4,"investing, Why March is so volatile for stocks",New York (CNN Business)March Madness isn't jus...

In [26]:
df['Keywords'][0]

"world, There's a shortage of truckers, but TuSimple thinks it has a solution: no driver needed"

In [37]:
df.drop(columns= ['Keywords'], inplace=True, axis=1)

In [47]:
df['Article text'] = df['Article text'].str.lower()

In [35]:
from transformers import BartTokenizer, BartForConditionalGeneration

In [36]:
model_name = "facebook/bart-large-cnn"

tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name)

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

In [69]:
from tqdm import tqdm
summaries = []

for i in tqdm(df['Article text'][:10]):
    tokenized = tokenizer(i, return_tensors='pt', max_length=1024, truncation=True)
    summary = model.generate(tokenized['input_ids'])
    decoded = tokenizer.decode(summary[0], skip_special_tokens=True)
    summaries.append(decoded)

  0%|          | 0/10 [00:00<?, ?it/s]

100%|██████████| 10/10 [05:41<00:00, 34.19s/it]

In [71]:
print(summaries[0])

Tusimple has completed about 2 million miles of road tests with its 70 prototype trucks across the us, china and europe. yara birkeland is what its builders call the world's first zero-emission, autonomous cargo ship. hyperloop is like a bullet train, without tracks and rails, propelled through a low-pressure steel tube using magnetic levitation.

In [59]:
df['Article text'][0]

'right now, there\'s a shortage of truck drivers in the us and worldwide, exacerbated by the e-commerce boom brought on by the pandemic. one solution to the problem is autonomous trucks, and several companies are in a race to be the first to launch one. among them is san diego-based tusimple.founded in 2015, tusimple has completed about 2 million miles of road tests with its 70 prototype trucks across the us, china and europe. although these are simply commercially available trucks retrofitted with its technology, tusimple has deals in place with two of the world\'s largest truck manufacturers -- navistar in the us and traton, volkswagen\'s trucking business, in europe -- to design and build fully autonomous models, which it hopes to launch by 2024. photos: the yara birkeland is what its builders call the world\'s first zero-emission, autonomous cargo ship. the ship is scheduled to make its first journey between two norwegian towns before the end of the year. click through to see more forms of transport set to transform the future.hide caption 1 of 13 photos: pictured here as a rendering, oceanbird is a wind-powered transatlantic car carrier that cuts carbon emissions by 90%, compared to a standard car carrier.hide caption 2 of 13 photos: it\'s not just maritime ships that are going green. cities around the world are adopting electric ferries. norwegian startup zeabuz hopes its self-driving electric ferry (pictured here as a rendering) will help revive urban waterways.hide caption 3 of 13 photos: in china, a new maglev high-speed train rolls off the production line in qingdao, east china\'s shandong province, on july 20. it has a top speed of 600 km per hour -- currently the fastest ground vehicle available globally. hide caption 4 of 13 photos: reaching speeds of up to 1,000 kilometers (620 miles) per hour, hyperloop could be a sustainable replacement to short-haul flights. dutch company hardt (shown here as a rendering) started work on its hyperloop test facility in europe, anticipated to open in 2022.hide caption 5 of 13 photos: hyperloop is like a bullet train, without tracks and rails. floating pods are propelled through a low-pressure steel tube using magnetic levitation. virgin has been running tests with passengers on its xp-2 vehicle, pictured here.hide caption 6 of 13 photos: low carbon travel isn\'t just about switching to sustainable fuel sources -- it\'s also about redesigning the transport itself. a "flying-v" plane designed by delft\'s university of technology in the netherlands and dutch airline klm can cut fuel consumption by 20%. ultimately, researchers hope to switch out the kerosene with a sustainable fuel source, like liquid hydrogen.hide caption 7 of 13 photos: hydrogen aviation could provide a sustainable solution for short and medium-haul flights. in september, airbus unveiled plans for three hydrogen-powered, zero-emission aircraft which can carry 100 to 200 passengers. it hopes to launch the first zeroe aircraft in 2035.hide caption 8 of 13 photos: in december 2019, canadian airline harbour air flew the world\'s first all-electric, zero-emission commercial aircraft. the six-seater seaplane was retrofitted with magnix\'s magni500 all-electric motor. harbour air -- which carries half a million passengers annually -- hopes to become the world\'s first all-electric airline. hide caption 9 of 13 photos: in the case of electric bikes, the future is now: one retailer reported the sale of e-bikes and e-scooters had increased 230% this year. e-bikes give the user a boost to their pedaling, allowing them to go further with less effort. e-bikes are now even available on ride-share apps, like uber.hide caption 10 of 13 photos: while sleeper trains or buses might be the way most of us get some shut-eye on overnight travel, this rendering of a self-driving hotel suite from toronto-based designer steve lee of aprilli design studio might offer a plush alternative in the future.hide caption 11 of 13 photos: in the uae, these futuristic-looking pods are undergoing testing on a 400-meter line in sharjah, which borders dubai. belarus-based usky transport says its pods can help cities solve traffic problems.hide caption 12 of 13 photos: the coradia ilint by french rail transport company alstom is the world\'s first hydrogen-powered passenger train. it began testing in germany in 2018, and in september 2020 entered regular service in austria.hide caption 13 of 13no sleeptusimple\'s latest road test involved hauling fresh produce 951 miles, from nogales, arizona to oklahoma city. the pickup and the dropoff were handled by a human driver, but for the bulk of the route -- from tucson to dallas -- the truck drove itself. read more"today, because the system is not fully ready, we have a safety driver and a safety engineer on board at all times when we\'re testing, but we drove in full autonomy: the driver wasn\'t touching the wheel," said cheng lu, tusimple\'s president and ceo. the journey was completed in 14 hours versus the usual 24 with a human driver, mostly because a truck doesn\'t need to sleep. "in the us, a driver can only work 11 hours a day. we simply had a handoff when our first pair of drivers had to stop because they reached their 11 hours of operation," said lu. that, of course, negates the advantage of an autonomous system, so the idea is that once tusimple\'s trucks hit the market, there will be no need to have anyone onboard. picking up the watermelons still required the human touch.unlike self-driving cars, which are a still a way from being commercially available, tusimple trucks won\'t be required to operate in bustling city traffic, but only on stretches of highway that have been thoroughly mapped via the company\'s own software. "we collect data from the roads, and we create this very detailed, high definition map of each route. that adds another layer of safety for the vehicles," said lu. as a result, tusimple\'s trucks will only be able to self-drive along these pre-mapped trade corridors, which lu calls "virtual railroads," and nowhere else. this swarm of robots gets smarter the more it worksaccording to the company, in the us 80% of goods travel through just 10% of the nation\'s trade corridors, so even selective mapping allows for capturing a large portion of the business. tusimple is currently mapping routes between arizona and texas, and plans to have mapped routes across the nation by 2024. its plans are dependent on state legislation, however, because currently some states do not allow for testing of autonomous trucks on public roads. happier drivers?the technology will add about $50,000 to the cost of a truck, making the final price roughly $200,000. according to lu, that\'s still cheaper than paying for a human driver. "if you take $50,000 and divide it by 1 million miles, the average lifespan of a truck, that means you\'re adding five cents per mile. but you\'re saving the cost of a human driver, which based on average us wages is about $80,000 to $120,000 per year -- or 80 cents to $1.20 per mile. today, the direct labor cost is about 50% of the cost of operating a truck," he said. read: a robotic \'ironhand\' could protect factory workers from injuriesthat doesn\'t mean driverless trucks will take away jobs, according to lu. by focusing on the "middle mile," rather than on the pickup and delivery of the goods, tusimple believes it can create new freight capacity without creating new demand for drivers, while at the same time protecting existing jobs. "a ups driver is dropping off 200 packages a day -- that\'s not what autonomy is meant for. we believe that every driver will be able to retire as a driver, even if they enter the workforce today," said lu. tusimple\'s autonomous fleet.instead, tusimple aims to take over the routes between terminals and distribution centers, which involve long stretches of monotonous driving. "take phoenix to el paso: that\'s a six-hour drive. a person cannot make the round trip, because it\'s more than 11 hours. but the truck can go back and forth all day, the most mundane job that drivers don\'t want to do. that means you free up that human driver to do the first and the last mile (pickup and delivery).they get to work a full day, which is a more efficient use of their time, and they get to go home at night to their family," said lu.no distractions although lu says that the reliability of both the software and the hardware still needs to be increased, tusimple is planning its first fully autonomous tests, without a human safety driver in the cabin at all, before the end of the year. the results of such tests will indicate whether the company can meet its goal to launch its own trucks by 2024. lu says that 7,000 have been reserved in the us alone. photos: the robots running our warehouses photos: the robots running our warehousesrobots are an increasingly familiar presence in warehouses. at the south-east london warehouse run by british online supermarket ocado, 3,000 robots fulfill shopping orders. when an order is sent to the warehouse, the bots spring to life and head towards the container they require. scroll through to see more robots that are revolutionizing warehouses.hide caption 1 of 8 photos: the robots running our warehousesin response to the coronavirus pandemic, mit collaborated with ava robotics and the greater boston food bank to design a robot that can use uv light to sanitize the floor of a 4,000-square foot warehouse in just 30 minutes. hide caption 2 of 8 photos: the robots running our warehousesseven-foot "model-t" robots produced by japanese startup telexistence have been stacking shelves in two of tokyo\'s largest convenience store franchises. featuring cameras, microphones and sensors, the model-t uses three "fingers" to stock items such as bottled drinks, cans and rice bowls. the robot is controlled by shop staff remotely.hide caption 3 of 8 photos: the robots running our warehousesus company boston dynamics has become known for its advanced work robots. "handle" is made for the warehouse and equipped with an on-board vision system. it can lift boxes weighing over 30 pounds. hide caption 4 of 8 photos: the robots running our warehousesstretch is the latest robot from boston dynamics and can work in warehouses and distribution centers. designed to keep human workers out of harm\'s way, stretch\'s tentacle-like grippers mean it can manipulate boxes. hide caption 5 of 8 photos: the robots running our warehousesalthough not specifically designed for warehouses, boston dynamics\' dog-like robot "spot" can lift objects, pick itself up after a fall, open and walk through doors, and even remind people to practice social distancing. hide caption 6 of 8 photos: the robots running our warehousesthis robot is used to plant seeds and check plants at the "nordic harvest" vertical farm  based in taastrup, denmark. the indoor farm is one of the biggest in europe.hide caption 7 of 8 photos: the robots running our warehousesrobots sort packages at a warehouse run by jd.com -- one of china\'s largest e-commerce firms, in wuhan, china, ahead of the annual singles day online shopping bonanza, in 2019.hide caption 8 of 8 tusimple has prominent competitors, such as google spinoff waymo and uber-backed aurora, but those are working on a wider range of self-driving vehicles, including passenger cars. tusimple is working exclusively on driverless trucks, like us companies plus and embark. grayson brulte, an autonomy expert at consulting firm brulte & co., believes tusimple is on the right track. "the biggest competitive advantage that tusimple has over its competitors is that their technology was purpose-built for trucking. they\'re not trying to port an autonomy system built for passenger vehicles in dense urban environments to trucking or to build a virtual driver which can both drive passenger vehicles and class-8 trucks. these are different skills and different systems altogether," he said. removing the human element on long trucking routes has other benefits. the company says its trucks react 15 times faster than human drivers, and can see farther down the road, even at night. "in the us every year there are about 5,000 fatalities involving trucks, and most are due to human error," said lu. "the truck doesn\'t get tired, doesn\'t watch a movie or look at a phone. it doesn\'t get distracted."'